
site_name: Crawling System for Unreal Engine
site_url: https://nesjett.github.io/unreal-engine-crawling-system/
repo_url: https://www.unrealengine.com/marketplace/en-US/product/crawling-system-prone
site_description: Allow your players and AI to crawl along a spline with multiple options. Ready for first person and third person in Unreal Engine 4.X and 5.X
site_author: Nestor Sabater
copyright: All rights reserved

markdown_extensions:
  - customblocks

nav:
  - Home: '/'


theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.path
    - toc.follow
    - toc.integrate
    - navigation.top
    - navigation.footer


extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/channels/685799359308365851/685799359765676064
      name: Support Discord Channel

    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/nsabater.dev/
      name: Instagram

    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/NestorSabater
      name: Youtube channel

